import React, { useState, useEffect } from 'react';
import { Link, useSearchParams, useNavigate } from 'react-router-dom';
import { Search, Plus, User, Calendar, ChevronRight, X, Save, FileText } from 'lucide-react';
import { Patient } from '@/types/patient';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import { useNotification } from '@/context/NotificationContext';
import { usePatients } from '@/context/PatientContext';
import { useRole } from '@/context/RoleContext';

export function Patients() {
  const { patients, addPatient } = usePatients();
  const { role } = useRole();
  const [searchParams, setSearchParams] = useSearchParams();
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState('');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isHistoryModalOpen, setIsHistoryModalOpen] = useState(false);
  const { addNotification } = useNotification();

  useEffect(() => {
    if (searchParams.get('action') === 'register') {
      setIsHistoryModalOpen(true);
      // Clear the param so it doesn't reopen on refresh
      const newParams = new URLSearchParams(searchParams);
      newParams.delete('action');
      setSearchParams(newParams);
    }
  }, [searchParams, setSearchParams]);

  // New Patient Form State
  const [newPatient, setNewPatient] = useState({
    firstName: '',
    lastName: '',
    dateOfBirth: '',
    gender: 'male',
    mrn: '',
    email: '',
    phone: ''
  });

  const handleAddPatient = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Check if MRN already exists in local state to provide a better error message
    if (newPatient.mrn) {
      const existingByMrn = patients.find(p => p.mrn === newPatient.mrn);
      if (existingByMrn) {
        addNotification('Error', `Ya existe un paciente registrado con el MRN ${newPatient.mrn} (${existingByMrn.lastName}, ${existingByMrn.firstName}).`);
        return;
      }
    }

    const patient: Patient = {
      id: '', // Will be generated by Supabase
      firstName: newPatient.firstName,
      lastName: newPatient.lastName,
      dateOfBirth: newPatient.dateOfBirth,
      gender: newPatient.gender as 'male' | 'female' | 'other',
      mrn: newPatient.mrn || `HC-${new Date().getFullYear()}-${Math.floor(Math.random() * 1000)}`,
      lastVisit: new Date().toISOString(),
      contact: {
        phone: newPatient.phone,
        email: newPatient.email,
        emergencyContact: ''
      },
      history: {
        chiefComplaint: '',
        historyOfPresentIllness: '',
        pastMedicalHistory: [],
        familyHistory: [],
        socialHistory: ''
      },
      medications: [],
      clinicalScales: [],
      imagingStudies: [],
      alerts: []
    };

    try {
      await addPatient(patient);
      addNotification('Paciente Registrado', `${patient.firstName} ${patient.lastName} ha sido registrado exitosamente.`);
      
      // Notify Specialist if current user is Assistant
      if (role === 'assistant') {
        addNotification('Aviso al Especialista', `La asistente ha registrado un nuevo paciente: ${patient.firstName} ${patient.lastName}`, 'info');
      }

      setIsModalOpen(false);
      setNewPatient({
        firstName: '',
        lastName: '',
        dateOfBirth: '',
        gender: 'male',
        mrn: '',
        email: '',
        phone: ''
      });
    } catch (error: any) {
      console.error('Error adding patient:', error);
      
      if (error.isLocalSave) {
        addNotification('Guardado Local', error.message);
        setIsModalOpen(false);
        setNewPatient({
          firstName: '',
          lastName: '',
          dateOfBirth: '',
          gender: 'male',
          mrn: '',
          email: '',
          phone: ''
        });
        return;
      }

      let errorMessage = 'No se pudo registrar al paciente.';
      
      if (error.message?.includes('patients_mrn_key')) {
        errorMessage = 'Ya existe un paciente con este número de Historia Clínica (MRN).';
      }
      
      addNotification('Error', errorMessage);
    }
  };

  const filteredPatients = Array.isArray(patients) ? patients.filter(patient => 
    (patient.lastName || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
    (patient.firstName || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
    (patient.mrn || '').toLowerCase().includes(searchTerm.toLowerCase())
  ) : [];

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">
            {role === 'doctor' ? 'Historial Clínico' : 'Gestión de Pacientes'}
          </h1>
          <p className="text-sm text-slate-500">
            {role === 'doctor' ? 'Consultar y registrar historiales clínicos de pacientes.' : 'Ver y administrar expedientes de pacientes.'}
          </p>
        </div>
        <div className="flex flex-col sm:flex-row items-center gap-3">
          <button 
            onClick={() => setIsHistoryModalOpen(true)}
            className="inline-flex items-center px-4 py-2 border border-slate-300 text-sm font-medium rounded-md shadow-sm text-slate-700 bg-white hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
          >
            <FileText className="-ml-1 mr-2 h-4 w-4 text-slate-400" />
            Registrar Historial
          </button>
          <button 
            onClick={() => setIsModalOpen(true)}
            className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-[#215732] hover:bg-[#1a4528] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
          >
            <Plus className="-ml-1 mr-2 h-4 w-4" />
            Agregar Paciente
          </button>
        </div>
      </div>

      {/* Search Bar */}
      <div className="relative max-w-md">
        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <Search className="h-5 w-5 text-slate-400" />
        </div>
        <input
          type="text"
          className="block w-full pl-10 pr-3 py-2 border border-slate-300 rounded-md leading-5 bg-white placeholder-slate-500 focus:outline-none focus:placeholder-slate-400 focus:ring-1 focus:ring-[#215732] focus:border-[#215732] sm:text-sm transition duration-150 ease-in-out"
          placeholder="Buscar por nombre o HC..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      {/* Patient List */}
      <div className="bg-white shadow-sm border border-slate-200 rounded-xl overflow-hidden">
        {filteredPatients.length === 0 ? (
          <div className="p-8 text-center text-slate-500">No se encontraron pacientes.</div>
        ) : (
          <ul role="list" className="divide-y divide-slate-200">
            {filteredPatients.map((patient) => (
              <li key={patient.id} className="hover:bg-slate-50 transition-colors">
                <Link to={`/patients/${patient.id}`} className="block px-6 py-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center min-w-0 gap-4">
                      <div className="h-10 w-10 rounded-full bg-slate-100 flex items-center justify-center flex-shrink-0">
                        <User className="h-5 w-5 text-slate-500" />
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm font-medium text-slate-900 truncate">
                          {patient.lastName}, {patient.firstName}
                        </p>
                        <p className="text-xs text-slate-500 truncate flex items-center mt-0.5">
                          <span className="font-mono mr-2">{patient.mrn}</span>
                          <span className="w-1 h-1 bg-slate-300 rounded-full mx-1"></span>
                          <span>{format(new Date(patient.dateOfBirth), 'd MMM, yyyy', { locale: es })}</span>
                          <span className="w-1 h-1 bg-slate-300 rounded-full mx-1"></span>
                          <span className="capitalize">{patient.gender === 'male' ? 'Masculino' : patient.gender === 'female' ? 'Femenino' : 'Otro'}</span>
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-6">
                      <div className="hidden sm:flex flex-col items-end">
                        <p className="text-xs text-slate-500 mb-1">Última Visita</p>
                        <div className="flex items-center text-sm text-slate-700">
                          <Calendar className="w-3 h-3 mr-1 text-slate-400" />
                          {format(new Date(patient.lastVisit), 'd MMM, yyyy', { locale: es })}
                        </div>
                      </div>
                      <ChevronRight className="h-5 w-5 text-slate-400" />
                    </div>
                  </div>
                </Link>
              </li>
            ))}
          </ul>
        )}
      </div>

      {/* Registrar Historial Modal */}
      {isHistoryModalOpen && (
        <div className="fixed inset-0 z-[100] overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
          <div className="flex min-h-screen items-center justify-center p-4 text-center">
            <div className="fixed inset-0 bg-slate-900/50 transition-opacity" aria-hidden="true" onClick={() => setIsHistoryModalOpen(false)}></div>

            <div className="relative w-full max-w-lg transform overflow-hidden rounded-2xl bg-white text-left align-middle shadow-xl transition-all">
              <div className="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-lg leading-6 font-medium text-slate-900" id="modal-title">
                    Seleccionar Paciente para Historial
                  </h3>
                  <button onClick={() => setIsHistoryModalOpen(false)} className="text-slate-400 hover:text-slate-500">
                    <X className="h-6 w-6" />
                  </button>
                </div>
                
                <div className="space-y-4">
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                      <Search className="h-4 w-4 text-slate-400" />
                    </div>
                    <input
                      type="text"
                      className="block w-full pl-10 pr-3 py-2 border border-slate-300 rounded-md leading-5 bg-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-[#215732] focus:border-[#215732] sm:text-sm"
                      placeholder="Buscar paciente..."
                      value={searchTerm}
                      onChange={(e) => setSearchTerm(e.target.value)}
                    />
                  </div>

                  <div className="max-h-60 overflow-y-auto border border-slate-200 rounded-md divide-y divide-slate-100">
                    {filteredPatients.length === 0 ? (
                      <div className="p-4 text-center text-slate-500 text-sm">No se encontraron pacientes.</div>
                    ) : (
                      filteredPatients.map(p => (
                        <button
                          key={p.id}
                          onClick={() => navigate(`/patients/${p.id}?edit=true&tab=history`)}
                          className="w-full text-left px-4 py-3 hover:bg-slate-50 flex items-center justify-between transition-colors"
                        >
                          <div>
                            <p className="text-sm font-medium text-slate-900">{p.lastName}, {p.firstName}</p>
                            <p className="text-xs text-slate-500">HC: {p.mrn}</p>
                          </div>
                          <ChevronRight className="h-4 w-4 text-slate-300" />
                        </button>
                      ))
                    )}
                  </div>

                  <div className="pt-4 border-t border-slate-100">
                    <p className="text-xs text-slate-500 mb-3">¿El paciente no está registrado?</p>
                    <button
                      onClick={() => {
                        setIsHistoryModalOpen(false);
                        setIsModalOpen(true);
                      }}
                      className="w-full inline-flex justify-center items-center rounded-md border border-slate-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-slate-700 hover:bg-slate-50 focus:outline-none"
                    >
                      <Plus className="mr-2 h-4 w-4 text-slate-400" />
                      Registrar Nuevo Paciente
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Add Patient Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-[100] overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
          <div className="flex min-h-screen items-center justify-center p-4 text-center">
            <div className="fixed inset-0 bg-slate-900/50 transition-opacity" aria-hidden="true" onClick={() => setIsModalOpen(false)}></div>

            <div className="relative w-full max-w-lg transform overflow-hidden rounded-2xl bg-white text-left align-middle shadow-xl transition-all">
              <div className="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-lg leading-6 font-medium text-slate-900" id="modal-title">
                    Registrar Nuevo Paciente
                  </h3>
                  <button onClick={() => setIsModalOpen(false)} className="text-slate-400 hover:text-slate-500">
                    <X className="h-6 w-6" />
                  </button>
                </div>
                
                <form onSubmit={handleAddPatient} className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-slate-700">Nombre</label>
                      <input
                        type="text"
                        required
                        className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-[#215732] focus:border-[#215732] sm:text-sm"
                        value={newPatient.firstName}
                        onChange={e => setNewPatient({...newPatient, firstName: e.target.value})}
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-700">Apellido</label>
                      <input
                        type="text"
                        required
                        className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-[#215732] focus:border-[#215732] sm:text-sm"
                        value={newPatient.lastName}
                        onChange={e => setNewPatient({...newPatient, lastName: e.target.value})}
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-slate-700">Fecha de Nacimiento</label>
                      <input
                        type="date"
                        required
                        className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-[#215732] focus:border-[#215732] sm:text-sm"
                        value={newPatient.dateOfBirth}
                        onChange={e => setNewPatient({...newPatient, dateOfBirth: e.target.value})}
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-700">Género</label>
                      <select
                        className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-[#215732] focus:border-[#215732] sm:text-sm"
                        value={newPatient.gender}
                        onChange={e => setNewPatient({...newPatient, gender: e.target.value})}
                      >
                        <option value="male">Masculino</option>
                        <option value="female">Femenino</option>
                        <option value="other">Otro</option>
                      </select>
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-slate-700">Historia Clínica (Opcional)</label>
                    <input
                      type="text"
                      placeholder="Generado automáticamente si se deja vacío"
                      className="mt-1 block w-full border border-slate-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-[#215732] focus:border-[#215732] sm:text-sm"
                      value={newPatient.mrn}
                      onChange={e => setNewPatient({...newPatient, mrn: e.target.value})}
                    />
                  </div>

                  <div className="mt-5 sm:mt-6">
                    <button
                      type="submit"
                      className="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-[#215732] text-base font-medium text-white hover:bg-[#1a4528] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 sm:text-sm"
                    >
                      <Save className="mr-2 h-4 w-4" />
                      Guardar Paciente
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
